name: Deploy| auth-server

on:
  workflow_dispatch:
  push:
  

env:
  SEARVICE_NAME: authe-server
  DOCKER_PATH: ./docker/Dockerfile
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/go-cloudrun-container/auth-server:${{ github.sha }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: GAR Authentication
        uses: ./.github/actions/gar-authentication
        with:
          sa-key: ${{ env.GCP_SA_KEY }}
          region: ${{ secrets.GCP_REGION }}

      - name: Build a docker image
        run: docker build -f ${{ env.DOCKER_PATH }} -t ${{ env.IMAGE }} .

      - name: Push the docker image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SEARVICE_NAME }}
          image: ${{ env.IMAGE }}
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: |
            ORIGIN=${{ secrets.ORIGIN_URL }} \
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            GOOGLE_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }} \
            APPLE_CLIENT_ID=${{ secrets.APPLE_CLIENT_ID }} \
            APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }} \
            APPLE_SECRET=${{ secrets.APPLE_SECRET }} 